//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoshoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string ArticleOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int AddressID { get; set; }
        public int UserID { get; set; }
        public int Code { get; set; }
        public int StatusID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
